### ISSUE TITLE
banner suppression adding single quotes

### ISSUE THREAD

**Issue by SID800** [Kintyre/ksconf#65]
# The problem

Suppressing the banner used with combine, its not working. Specifically, the empty string `''` is being added into the .conf files.  The desire is to omit the banner from conf files, unless it has been actually modified/merged from multiple sources (feature request #64) 

## Environment

* ksconf 0.7.7rc3  (Build 449)
* OS & version used: windows 
* Python version: 2.7.16  (c:\python27\python.exe)
* Installed via:  pip

## Details

command used: 
`ksconf combine default.d/* --target=default --disable-marker --banner ''`

which results in #'' in every conf file. 
![image](https://user-images.githubusercontent.com/12401288/66430365-cd651780-e9ce-11e9-94c6-8de4e65ffa1e.png)

using --banner without anything passed, results in an error
```
ksconf combine default.d/* --target=default --disable-marker --banner
usage: ksconf combine [-h] [--target TARGET] [--dry-run] [--banner BANNER]
                      [--disable-marker]
                      source [source ...]
ksconf combine: error: argument --banner/-b: expected one argument
```

**Comment by lowell80** [comment]
Yes, banner requires a single argument.   Try `--banner ""`.  I just tried it on Windows (CMD/batch) and it seems to work.  It looks like `''` is being passed to ksconf as a literal value.

**Comment by SID800** [comment]
confirmed `--banner "" ` works

I got '' from  https://ksconf.readthedocs.io/en/latest/cmd_combine.html

**Comment by lowell80** [comment]
Yup.  Found it and have updated it.  Thanks for the link.
