### ISSUE TITLE
Error displayed on execution - ValueError: unsupported hash type sha1

### ISSUE THREAD

**Issue by jonesy1234** [Kintyre/ksconf#68]
# The problem

When running ksconf the following error is displayed.

ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/opt/splunk/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/splunk/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1

## Environment

* Ksconf version:  ksconf 0.7.6  (Build 435)
* OS & version used: Oracle Linux Server release 7.7
* Python version: Python: 2.7.15  (/opt/splunk/bin/python)
* Installed via:  Splunk app
* Git SHA1 cf0cd07d committed on 2019-08-15
* Installed at: /opt/splunk/etc/apps/ksconf/bin/lib/ksconf

## Details

This is a fresh installation so I'm not sure what further details I can provide. KSCONF_DEBUG=1 doesn't display anymore detail other than the output below. As I'm using the python version from with the splunk app I'm assuming this is not an OS level issue?

```
[splunk]$ /opt/splunk/bin/splunk cmd python /opt/splunk/etc/apps/ksconf/bin/install.py
ksconf_app: /opt/splunk/etc/apps/ksconf/bin
Writing script /opt/splunk/bin/ksconf
Try running 'ksconf --version' to ensure that install worked correctly.
[splunk]$ ksconf --version
-bash: ksconf: command not found
[splunk]$ /opt/splunk/bin/ksconf --version
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/opt/splunk/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/opt/splunk/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
                                  #
                                  ##
 ###  ##     #### ###### #######  ###  ##  #######
 ### ##     ###  ###           ## #### ##
 #####      ###  ###      ##   ## #######  #######
 ### ##     ###  ###      ##   ## ### ###  ##
 ###  ## #####    ######   #####  ###  ##  ##
                                        #

ksconf 0.7.6  (Build 435)
Python: 2.7.15  (/opt/splunk/bin/python)
Git SHA1 cf0cd07d committed on 2019-08-15
Installed at: /opt/splunk/etc/apps/ksconf/bin/lib/ksconf
Written by Lowell Alleman <lowell@kintyre.co>.
Copyright (c) 2019 Kintyre Solutions, Inc, all rights reserved.
Licensed under Apache Public License v2

    Commands:
      check           (stable)    OK
      combine         (beta)      OK
      diff            (stable)    OK
      filter          (alpha)     OK
      merge           (stable)    OK
      minimize        (beta)      OK
      promote         (beta)      OK
      rest-export     (beta)      OK
      rest-publish    (alpha)     Missing 3rd party module:  libssl.so.1.0.0: cannot open shared object file: No such file or directory
      snapshot        (alpha)     OK
      sort            (stable)    OK
      unarchive       (beta)      OK
      xml-format      (alpha)     OK   (lxml 4.3.0)
```

Example Traceback:

```
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/ksconf/bin/lib/ksconf/__main__.py", line 155, in cli
    return_code = args.funct(args)
  ...
  File "/opt/splunk/etc/apps/ksconf/bin/lib/ksconf/commands/restpublish.py", line 119, in connect_splunkd
    self._service = splunklib.client.connect(
AttributeError: 'NoneType' object has no attribute 'client'
```

## Steps To Reproduce Issue

1. Splunk version 7.3.3 installation on Oracle Linux 7
2. Install via SplunkBase
3. Run any ksconf command

Thanks

**Comment by jonesy1234** [comment]
Found a reference to this and a fix. Closing. Thanks!

**Comment by lowell80** [comment]
Thanks for the full bug report!  I'm assuming the fix you found was related to #48?  Did you resolve this by simply calling `setSplunkEnv` or come up with another fix/workaround?  I'd like to improve the end-use experience here, but I'm not 100% sure what would work best.

Thanks for trying out ksconf and taking the time to file a bug report!

**Comment by jonesy1234** [comment]
Hey thanks for getting in touch. Great tool you have built here I think Splunk really need to integrate version control within the core app but doesn’t seem to be coming any time soon....

Running through splunk cmd works best for me as I’m planning on merging local to default changes through from a power users splunk host via an ansible playbook, checkin to git and trigger CI/CD to promote bundle across our search head cluster. 

We host our shcluster apps in CodeCommit and have a CloudWatch event trigger to run the bundle deploy via ansible. On the power user splunk host these apps are checked out and symlinked to etc/apps.

Anyway blog post coming soon... I’ll make sure I give your great work a shout out 😉

Many thanks 👍

**Comment by brian-kennedy** [comment]
Hi Steven,

I'm glad you are seeing the value of KSCONF.  To help us promote the tool,
how did you come across it?  I want to assume Splunkbase?

--
BRIAN KENNEDY
*kintyre <http://kintyre.co/>.  Splunk Expertise & System Craftsmanship.*
(302) 482-4571 | about.me/brian.m.kennedy
Splunk Certified Architect and Sales Engineer, AWS Certified Architect

**Comment by jonesy1234** [comment]
Afraid not, it was via google when searching how the hell others had done this sort of thing managing app config in git. Found the presentation/talk that was done.

Cheers

**Comment by brian-kennedy** [comment]
Thanks for the feedback!


--
Brian Kennedy 
(302)482-4571
