### ISSUE TITLE
promote command with non-interactive list of stanzas

### ISSUE THREAD

**Issue by mthambipillai** [Kintyre/ksconf#75]
## Is your feature request related to a problem? Please describe.

First of all, thanks a lot for providing such a great tool! We want to improve our Splunk development and deployment process at our company and KSCONF matches almost perfectly our needs!
"almost" because of the following:

We're using a Git repo for our shared Splunk cluster and we already have some guidelines for users on how they should use `ksconf promote` to move their changes from local to default. They can use the interactive mode to select the stanzas they want to promote.

Now we would like to automate this process on Jenkins (create a PR, use ksconf to promote). If a user wants to promote all stanzas of a file let's say macros.conf, the process can be fully automated by Jenkins. But if a user wants to promote only some stanzas, the interactive mode must be used, which cannot easily be automated with Jenkins because the user must select yes/no for every stanza.

## Describe the solution you'd like

I would like to have another option to the `ksconf promote` command called let's say `--stanzas-list` that would take a string of stanzas names separated by commas as argument. Behind the scenes the option would work exactly like the interactive mode, but requires the user's input only once at the beginning.

The command would log some error in case a stanza's name is not recognized.

example:

```ksconf promote --stanzas-list s1,s3```

similar to:

```ksconf promote --interactive
stanza s1?
>yes
stanza s2?
>no
stanza s3?
>yes
stanza s4?
>no
```

## Describe alternatives you've considered

I considered building a script on top of ksconf to launch the interactive mode, parse the response and provide the correct user input, but it seems cleaner and easier to incorporate this functionality in ksconf itself, plus it might be useful to other people.

## How serious are you about this change?  [ For not-trivial changes ]

Quite serious, I'd be happy to implement the change myself if I can have some guidance on where exactly in the code this functionality could be added.

**Comment by lowell80** [comment]
Hey Melchior, thanks for taking the time to reach out and describe your use case.  This is a very reasonable ask, and I agree that it has value to a wider audience.  (It was never my intention that the only options would be `--interactive` or `--batch`.  I've always wanted additional functionality, and this has been in my mental backlog for some time, but unfortunately I have more ideas than time/energy.)  So if you're willing to dig in, I'm glad to help get this feature part of the core product.

# Getting started

If you haven't seen these, start here:

* https://ksconf.readthedocs.io/en/latest/contrib.html
* https://ksconf.readthedocs.io/en/latest/devel.html

Technical resources:

* Source code:  https://github.com/Kintyre/ksconf/blob/master/ksconf/commands/promote.py
* Unit tests: https://github.com/Kintyre/ksconf/blob/master/tests/test_cli_promote.py
* Docs:  https://github.com/Kintyre/ksconf/blob/master/docs/source/cmd_promote.rst


# Thoughts about promote / filter intersection

In terms of what I'd like to see in an interface is really this.  I'd like some feature parity between the `ksconf filter` command and `ksconf promote`.  It's quite likely that this wouldn't be 1:1, and it certainly doesn't need to be in the first published version (that can be more of a long-term goal), but I want to be thoughtful with the CLI options and consistent and avoid breaking peoples scripts when they upgrade to a new version.  But at the heart of the question is "what should be promoted?" and `filter` deals with that idea, so I'd like to reuse, what's possible.

At the "risk" of giving you an alternative that doesn't result it a PR and improved code :-), if you only care about getting the right content in default file, and don't care about what ends up in the local file, then you may be able to get what you want right now by using `filter` and `promote` back-to-back.  (Hopefully this also illustrates the logical connection I'm drawing between filter and promote commands).   Suppose you have the following conf files (expanding on your example) to promote:

```
$ cat default/my.conf
[s1]
a = 1
x = 99
[s4]
x = 99

$ cat local/my.conf
[s1]
x = 1
[s2]
x = 2
[s3]
x = 3
[s4]
x = 4
```

You could promote just `s1` and `s3` by running:

```
ksconf filter local/my.conf --stanza s1 --stanza s3 > local/my.conf-promote
ksconf promote local/my.conf-promote default/my.conf --batch --force
```

The output (`default/my.conf`) would now look like this:
```
[s1]
a = 1
x = 1
[s3]
x = 3
[s4]
x = 99
```

So `s1`'s `x` was updated, and `s3` was copied (new), leaving `s2` and `s4` untouched.

But the big limitation here is:

 1. `local/my.conf` is *not* updated.  (I'm guessing it would be possible using some other combination of `ksconf` commands, but it gets to be a logical mess.)
 1. It requires two commands and a temporary file (not user friendly)

Ideally, `ksconf` should support a syntax like so:

    ksconf promote local/my.conf default/my.conf --stanza s1 --stanza s2

Possible filter CLI arguments that could be relevant to promote include:  `--stanza PATTERN`, `--attr-present ATTR`, `--keep-attrs WC-ATTR` and `--reject-attrs WC-ATTR`, and possibly selection control arguments such as `--invert-match` and `--ignore-case`.

I think for starters just adding `--stanza` would be good enough.

**Comment by lowell80** [comment]
I refactored some of the `filter` internals so that they could be re-used by the `promote` command too.  As a result, I have `promote --stanza` working for both batch and interactive modes, (`ksconf --batch --stanza 'x'` is what you want for your use case.)  And it supports (1) reading a list of stanzas from a file, case sensitivity, match inversion, and various matching modes (string/regex/wildcard). I also added a `--summary` mode which you can used to get a quick listing of which stanzas could be promoted.

I had a question regarding the warning/non-0-exit code when one of the stanza values was missing in the PR (#76), but that closed automatically when I merged it; and unlike GH issues, it looks like you can't explicitly re-open it.  Still figuring out some of those details.

If you have a few moments, please give 0.7.8rc1 a try:
```
pip install -U kintyre-splunk-conf==v0.7.8rc1
```

Longer release notes here.  I also update the promote documentation page.
https://ksconf.readthedocs.io/en/latest/changelog.html#release-v0-7-8-draft

Thanks again for your contribution on this!  If it all works as expected I'll try to get an official release out next week.

**Comment by mthambipillai** [comment]
Thanks a lot! I will give the beta a try!

**Comment by mthambipillai** [comment]
I tested 0.7.8rc1 and it works as expected! Thanks a lot this will be very helpful! :)

**Comment by lowell80** [comment]
@mthambipillai, please note that 0.7.8 has been officially released.  If you run into further issues on this feel free to reopen.  Thanks again for all your help making ksconf a more useful tool!
