### ISSUE TITLE
promote summary does not support --stanza filtering

### ISSUE THREAD

**Issue by guilhemmarchand** [Kintyre/ksconf#89]
# The problem

We are using the promote --summary before performing the promotion, such that we can log and investigate the changes reported by the use case owners.

I am noticing that the summary option (-s) does not work with stanza filtering, there will be no output, however the promote itself works perfectly fine,

## Environment

* Ksconf version:  0.8.7
* OS & version used: RHEL 7
* Python version: 3.7.4 
* Installed via:  Splunk app

## Details

```
/opt/splunk/bin/ksconf promote -s --stanza "gsocsan_cim_Application_State_indexes" /opt/splunk/etc/apps/SA-0-Framework-BRAZIL/local/macros.conf /opt/software/sync_workspace/SA-0-Framework-BRAZIL/default/macros.conf
```

--> no changes reported, but we have one stanza to be promoted.

```
/opt/splunk/bin/ksconf promote -s /opt/splunk/etc/apps/SA-0-Framework-BRAZIL/local/macros.conf /opt/software/sync_workspace/SA-0-Framework-BRAZIL/default/macros.conf
Have 1 'replace' operations:
	[gsocsan_cim_Application_State_indexes]  1 keys
```

**Comment by lowell80** [comment]
@guilhemmarchand , please take a look at v0.8.8rc3 and see if it better address this request.  I'm not 100% sure it's behaving correctly, but I stared at it long enough I could use another pair of eyes.

**Comment by lowell80** [comment]
Okay, I'm pretty sure this is fixed now.  I've also added `--diff` mode that should help be like a "preview" of what will be applied.

I've just release v0.8.8r4 (which may end up being officially released as 0.9.0, we'll see).

I'll be out on vacation for a week, so I'll review any feedback and pushing a release then.  I got a bunch of random things addressed.

**Comment by guilhemmarchand** [comment]
Hi @lowell80 !
Sorry for late replying, I am back from PTO as well and back with my customer using ksconf ;-)
So I am about to verify this, and will let you know very shortly!

**Comment by lowell80** [comment]
@guilhemmarchand, cleaning up old tickets.  Please re-open if this doesn't work as expected.
